version: "3.8"

networks:
    awesome:
        driver: bridge

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: awesome
        container_name: awesome-app
        restart: unless-stopped
        working_dir: /var/www
        environment:
            APP_KEY: ${APP_KEY}
        volumes:
            - ./:/var/www
        networks:
            - awesome
    nginx:
        image: nginx:1.22-alpine
        container_name: awesome-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - awesome
    db:
        image: mysql
        container_name: awesome-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - awesome
